<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
  <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px"
           size="default" @submit.native.prevent>
    <el-form-item label="医生id" prop="id">
      <el-input v-model="formData.id" readonly="true" type="text"></el-input>
    </el-form-item>
    <el-form-item label="医生姓名" prop="name">
      <el-input v-model="formData.name" readonly="true" type="text"></el-input>
    </el-form-item>
    <el-form-item label="所属医院" prop="hospital_name">
      <el-input v-model="formData.hospital_name" type="text" clearable></el-input>
    </el-form-item>
    <el-form-item label="所属部门" prop="department_name">
      <el-input v-model="formData.department_name" type="text" clearable></el-input>
    </el-form-item>
    <el-form-item label="职称" prop="professional_rank">
      <el-radio-group v-model="formData.professional_rank">
        <el-radio v-for="(item, index) in professional_rankOptions" :key="index" :label="item.value"
                  :disabled="item.disabled" style="{display: inline}">{{item.label}}</el-radio>
      </el-radio-group>
    </el-form-item>
    <el-form-item label="专业方向" prop="study_direction">
      <el-input v-model="formData.study_direction" type="text" clearable></el-input>
    </el-form-item>
    <el-form-item label="自我介绍" prop="description">
      <el-input type="textarea" v-model="formData.description" rows="3"></el-input>
    </el-form-item>
    <el-form-item>
      <el-button type="primary" size="large" @click="submitForm">更新</el-button>
      <el-button type="info" size="large" @click="takeDoctorInfo">取消</el-button>
    </el-form-item>
  </el-form>

</template>

<script>
import {takeDoctorInfo, updateDoctorInfo} from "@/api/doctor";

export default {
  components: {},
  props: {},
  data() {
    return {
      formData: {
        id: "",
        name: "",
        hospital_name: "",
        department_name: "",
        professional_rank: 1,
        study_direction: "",
        description: "",
      },
      rules: {
        id: [{
          required: true,
          message: '字段值不可为空',
        }],
        name: [{
          required: true,
          message: '字段值不可为空',
        }],
        hospital_name: [{
          required: true,
          message: '字段值不可为空',
        }],
        department_name: [{
          required: true,
          message: '字段值不可为空',
        }],
        professional_rank: [{
          required: true,
          message: '字段值不可为空',
        }],
      },
      professional_rankOptions: [{
        "label": "主任医师",
        "value": "主任医师"
      }, {
        "label": "副主任医师",
        "value": "副主任医师"
      }, {
        "label": "主治医师",
        "value": "主治医师"
      }, {
        "label": "医师",
        "value": "医师"
      }],
    }
  },
  created() {
    this.takeDoctorInfo();
  },
  methods: {
    submitForm() {
      this.$refs['vForm'].validate(valid => {
        if (!valid) {
          return;
        }
        //TODO: 提交表单
        let pRank = 1;
        switch (this.formData.professional_rank) {
          case "主任医师": pRank = 1; break;
          case "副主任医师": pRank = 2; break;
          case "主治医师": pRank = 3; break;
          case "医师": pRank = 4; break;
        }
        let params = {
          hospital_name: this.formData.hospital_name,
          department_name: this.formData.department_name,
          professional_rank: pRank,
          study_direction: this.formData.study_direction,
          description: this.formData.description,
        };
        updateDoctorInfo(params).then((res) => {
          if (res.code === 200) {
            this.$message.success("更新成功!");
            this.takeDoctorInfo();
          } else {
            this.$message.error(res.msg);
          }
        });
      })
    },
    resetForm() {
      this.$refs['vForm'].resetFields()
    },
    takeDoctorInfo() {
      let params = {};
      takeDoctorInfo(params).then((res) => {
        if (res.code === 200) {
          this.formData = res.data.doctor;
        } else {
          this.$message.error(res.msg);
        }
      });
    },
  }
}

</script>

<style scoped>

</style>